<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Hospital_Mangament_System.BLL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital Managment System.DAL\Hospital Managment System.DAL.csproj" />
  </ItemGroup>

</Project>
